#
# Makefile.cvs
#

LIB = $(shell y2tool get-lib)

PREFIX = /usr

configure: 
	mkdir -p build ;\
	cd build ;\
	cmake -DCMAKE_INSTALL_PREFIX=$(PREFIX) -DLIB=$(LIB) .. && make

# use "VERBOSE=1 make" to read full gcc argument

install: configure
	cd build ;\
	make && make install

reconf: 
	cd build ;\
	cmake rebuild_cache

