SET( ${TARGETLIB}_SOURCES
  dummy.cc
  test.cc
  Y2CCGtk.cc
  YGBarGraph.cc
  YGComboBox.cc
  YGDialog.cc
  ygdkmngloader.c
  YGDumbTab.cc
  YGFrame.cc
  YGImage.cc
  YGInputField.cc
  YGIntField.cc
  YGLabel.cc
  YGLayout.cc
  YGMenuButton.cc
  YGPackageSelectorPluginStub.cc
  YGProgressBar.cc
  YGPushButton.cc
  YGRadioButton.cc
  YGSelectionStore.cc
  YGText.cc
  ygtkbargraph.c
  ygtkfieldentry.c
  ygtkfixed.c
  ygtkhtmlwrap.c
  ygtkimage.c
  ygtklinklabel.c
  ygtkmenubutton.c
  ygtkratiobox.c
  ygtkrichtext.c
  ygtksteps.c
  ygtktextview.c
  ygtktimezonepicker.c
  ygtktreeview.c
  ygtkwindow.c
  ygtkwizard.c
  YGTreeView.cc
  YGUI.cc
  YGUtils.cc
  YGWidget.cc
  YGWizard.cc
)

SET( ${TARGETLIB}_HEADERS
  YGDialog.h
  ygdkmngloader.h
  YGi18n.h
  YGPackageSelectorPluginIf.h
  YGSelectionStore.h
  ygtkbargraph.h
  ygtkfieldentry.h
  ygtkfixed.h
  ygtkhtmlwrap.h
  ygtkimage.h
  ygtklinklabel.h
  ygtkmenubutton.h
  ygtkratiobox.h
  ygtkrichtext.h
  ygtksteps.h
  ygtktextview.h
  ygtktimezonepicker.h
  ygtktreeview.h
  ygtkwindow.h
  ygtkwizard.h
  YGUI.h
  YGUtils.h
  YGWidget.h
)
